### ISSUE TITLE
Build WASM Compiler for ByteScript Language

### ISSUE THREAD

**Issue by p3nGu1nZz** [bytescript/bytescript#28]
### Abstract

Our goal is to develop a wasm compiler for a script language. The project involves several stages, including creating a Lexer to tokenize the script language source code, a parser to generate an Abstract Syntax Tree (AST) from the tokens, and a code generator to generate web assembly binary from the AST. Additionally, the project involves creating a runtime library to support WASI system calls, an optimizer to optimize the generated web assembly binary, and a linker to link the generated web assembly binary with the runtime library. The final stage of the project involves testing the compiler with both sample and more complex script language source code to ensure its correctness and efficiency.

### Example

Our goal is to transform this simple and valid bytescript code into a wat format that can run.

```ts
function add(a: i32, b: i32): i32 {
  return a + b
}

export { add }
```

This is how the wat text in binary form should appear.

```wat
(module
    (func $add (param $a i32) (param $b i32) (result i32)
      (i32.add
        (local.get $a)
        (local.get $b)
      )
    )
    (export "add" (func $add))
)
```

This example discusses the goal of building a WASM compiler for ByteScript language. The syntax is minimal but valid and is already supported. The following issue mentions some of the challenges and future work that need to be addressed. This project is an exciting opportunity to explore the potential of ByteScript as a high-level language for WebAssembly.

### Tasks

- [ ] #32 
- [ ] Create a parser to generate an Abstract Syntax Tree (AST) from the tokens. 
- - [ ] Define the grammar of the script language using a formal grammar notation such as Backus-Naur Form (BNF) or Extended Backus-Naur Form (EBNF)
- - [ ] Write a parser that can recognize the grammar and generate an Abstract Syntax Tree (AST) from the tokens produced by the lexer.
- - [ ] Implement error handling and recovery mechanisms in the parser to handle syntax errors in the source code.
- - [ ] Test the parser with sample script language source code to ensure it generates the correct AST.
- [ ] Create a code generator to generate web assembly binary from the AST. 
- - [ ] Write a code generator that can traverse the Abstract Syntax Tree (AST) generated by the parser and generate web assembly instructions for each node in the AST.
- - [ ] Implement a register allocator to assign registers to variables and expressions in the script language source code.
- - [ ] Implement an instruction selector to choose the most efficient web assembly instructions to implement the operations in the script language source code.
- - [ ] Test the code generator with sample script language source code to ensure it generates correct and efficient web assembly binary.
- [ ] Test the compiler with sample script language source code 
- - [ ] Write test cases for the sample script language source code.
- - [ ] Run the compiler on the sample script language source code to generate web assembly binary.
- - [ ] Verify natively:
- - - [ ] Compare the output of the web assembly binary with expected output using WASIX
- - - [ ] Check for any runtime errors or crashes
- - [ ] Verify in browser:
- - - [ ] Compare output of web assembly binary with expected output using WASI
- - - [ ] Check for any runtime errors or crashes
- [ ] Create a runtime library to support WASI system calls.
- - [ ] Research the WASI system call API and understand the functionality provided by each system call.
- - [ ] Write functions in the runtime library to implement each WASI system call using the host system’s native system calls.
- - [ ] Test each function in the runtime library to ensure it correctly implements the corresponding WASI system call.
- - [ ] Integrate the runtime library with the generated web assembly binary to provide WASI system call support.
- [ ] Create a linker to link the generated web assembly binary with the runtime library.
- - [ ] Write a linker that can read the symbol table of the generated web assembly binary and the runtime library.
- - [ ] Resolve any undefined symbols in the web assembly binary by searching for matching symbols in the runtime library.
- - [ ] Relocate any addresses in the web assembly binary that need to be adjusted based on the location of the runtime library in memory.
- - [ ] Generate a new web assembly binary that includes both the original web assembly binary and the runtime library, with all symbols resolved and addresses relocated.
- [ ] Create an optimizer to optimize the generated web assembly binary.
- - [ ] Write an optimizer that can analyze the control flow and data flow of the generated web assembly binary.
- - [ ] Implement optimization techniques such as constant folding, dead code elimination, and instruction scheduling to improve the performance of the web assembly binary.
- - - [ ] Implement constant folding by evaluating constant expressions at compile-time and replacing them with their computed values in the web assembly binary.
- - - [ ] Implement dead code elimination by identifying and removing code that does not affect the program’s output from the web assembly binary.
- - - [ ] Implement instruction scheduling by reordering instructions to reduce stalls and improve the performance of the web assembly binary.
- - [ ] Test the optimizer with sample script language source code to ensure it generates correct and more efficient web assembly binary.
- [ ] Test the compiler with more complex script language source code.
- - [ ] Verify the correctness of the generated web assembly binary.
- - [ ] Measure the performance of the generated web assembly binary.

### Conclusion

In conclusion, the checklist provides outlines for a comprehensive plan of developing a compiler for a script language. The project involves several stages, including creating a Lexer, parser, and code generator, as well as a runtime library, optimizer, and linker. The final stage involves testing the compiler to ensure its correctness and efficiency.

### References

- "Abstract Syntax Tree." *Wikipedia*, Wikimedia Foundation, https://en.wikipedia.org/wiki/Abstract_syntax_tree.
- "Lexical Analysis." *Wikipedia*, Wikimedia Foundation, https://en.wikipedia.org/wiki/Lexical_analysis.
- "Backus–Naur Form." *Wikipedia*, Wikimedia Foundation, https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form.
- "WebAssembly System Interface." *Wikipedia*, Wikimedia Foundation, https://en.wikipedia.org/wiki/WebAssembly_System_Interface.
- "WebAssembly." *Wikipedia*, Wikimedia Foundation, https://en.wikipedia.org/wiki/WebAssembly.
- "WASI." *WASI*, Bytecode Alliance. 
https://wasi.dev/.
