### ISSUE TITLE
Create a comprehensive list of all keywords in the script language

### ISSUE THREAD

**Issue by p3nGu1nZz** [bytescript/bytescript#33]
## Background:
In the development of our compiler, one of the key components is the lexer module. The lexer is responsible for breaking down the source code into a series of tokens that can be processed by the parser. Keywords are an important part of this process, as they are reserved words that have a special meaning in the script language and cannot be used as identifiers.

Creating a comprehensive list of all keywords in the script language is an essential step in the development of our lexer module. This list will help us ensure that our lexer can correctly identify and process all keywords in the script language. It will also help us and other developers understand the syntax and usage of each keyword in the script language.

This task is part of a larger effort to develop a robust and efficient compiler for our script language. By completing this task, we will be one step closer to achieving our goal.

## Description:
In this issue, we will focus on creating a comprehensive list of all keywords in the script language for our compiler. This task involves researching common keywords used in similar script languages, consulting with the development team to determine which keywords should be included, identifying any additional keywords specific to our script language, defining the syntax and usage for each keyword, writing a description of each keyword, providing examples of how each keyword can be used, adding each keyword to the list of keywords in our script language, and ensuring that the list is comprehensive and includes all relevant keywords.

## Task List:
- [x] Research common keywords used in similar script languages.
	- [x] Consult with the development team to determine which common keywords should be included in this script language.
	- [x] Identify any additional keywords specific to this script language.
- [x] Define the syntax and usage for each keyword in the script language.
	- [x] Write a description of each keyword, including its syntax and usage.
	- [x] Provide examples of how each keyword can be used in the script language.
- [x] Add each keyword to the list of keywords in the script language.
- [x] Ensure that the list of keywords is comprehensive and includes all relevant keywords for this script language.

## Documentation:
As part of this task, we will also document the process of creating the list of all keywords in the script language for our compiler. This documentation will include the sources, methods, and results of our research, as well as the descriptions and examples of each keyword. This documentation will help us and other developers understand the rationale and usage of each keyword in the script language.

To keep our documentation organized and accessible, we will create a new directory in our compiler to store our reference documentation for this task. The directory will be named "keywords" and will be located under the "docs" directory. The directory will contain a text file named "keywords.txt" that will contain the list of all keywords in the script language, along with their descriptions and examples. The directory will also contain any other relevant files or resources that we use or create during our research, such as links, notes, or diagrams.

Here is an example file structure for our documentation:

```
bytescript/
├── docs/
│   ├── compiler/
│   │   ├── lexer/
│   │   │   ├── keywords/
│   │   │   │   ├── keywords.md
│   │   │   │   ├── keywords.txt
│   │   │   │   └── ...
│   │   │   └── ...
│   │   └── ...
│   └── ...
└── ...
```

To create and update the documentation, we will use a text editor such as Visual Studio Code or Notepad++. We will follow a consistent format and style for writing the documentation, such as using headings, bullet points, indentation, and comments. We will also use proper grammar, spelling, and punctuation to ensure clarity and readability. We will review and revise the documentation as needed to ensure accuracy and completeness.

**Comment by ZoeDreams** [comment]
### TODO 

- [ ] Create a new directory called `keywords` in the `docs` directory of the project repository.
- [ ] Create a new text file called `keywords.md` in the `keywords` directory.
- [ ] Write an introduction paragraph that explains the purpose and scope of the list of keywords.
- [ ] Write a table of contents that links to each section of the list of keywords.
- [ ] Write a section for each category of keywords, such as literals, operators, control structures, etc.
- [ ] For each section, write a sub-section for each keyword in that category, such as `true`, `false`, `and`, `or`, `if`, `else`, etc.
- [ ] For each sub-section, write a brief description of the keyword, its syntax, its usage, and some examples.
- [ ] Write a conclusion paragraph that summarizes the list of keywords and provides some references or sources for further reading.
- [ ] Review and proofread the list of keywords for completeness, consistency, accuracy, and clarity.
- [ ] Run some tests or checks to verify that the list of keywords matches the script language specification and the lexer module.
- [ ] Commit and push the changes to the project repository and mark the issue as done.

**Comment by p3nGu1nZz** [comment]
I’ve finished making a list of all the keywords for our compiler and checked it against the script language spec and lexer module. Everything looks good, so I think we can close this issue now. Let me know if you have any questions or feedback.
