### ISSUE TITLE
Define the syntax for operators in the script language.

### ISSUE THREAD

**Issue by p3nGu1nZz** [bytescript/bytescript#34]
## Background

A script language is a type of [programming language](https://en.wikipedia.org/wiki/Scripting_language) that is used for writing scripts, which are short programs that automate tasks or add functionality to other programs. Script languages are often [interpreted](https://en.wikipedia.org/wiki/Interpreted_language), rather than compiled, which means that the source code is executed directly by the [interpreter](https://en.wikipedia.org/wiki/Interpreter_(computing)), rather than being translated into machine code and executed by the computer.

[Bytescript](https://github.com/bytescript/bytescript) is however a unique script language that allows you to script [web assembly](https://webassembly.org/) code that can be run in the browser or natively using precompiled [AOT (Ahead-of-Time) compilation](https://en.wikipedia.org/wiki/Ahead-of-time_compilation). This means that you can write scripts in bytescript and then compile them into web assembly code, which can be executed directly by the browser or by a [native runtime environment](https://en.wikipedia.org/wiki/Runtime_system) such as [wasmtime](https://github.com/bytecodealliance/wasmtime).

AOT compilation is a technique where the source code is compiled into machine code before it is executed, rather than being interpreted at runtime. This can improve the performance of the code by reducing the overhead of interpretation and allowing for more aggressive optimizations. [Here](https://en.wikipedia.org/wiki/Ahead-of-time_compilation) is a link to learn more about AOT compilation.

Operators are [special symbols](https://en.wikipedia.org/wiki/Symbol_(programming)) that represent specific operations to be performed on one or more operands, such as the `+` operator for addition or the `*` operator for multiplication. In bytescript, the syntax for operators defines how these symbols are written, used, and evaluated within the source code. Operators are essential in bytescript because they provide a way to perform basic arithmetic, logical, and comparison operations on data, which are fundamental building blocks of any program. Without operators, it would be much more difficult to write scripts that can manipulate data, control the flow of execution, and perform calculations.

## Description

In this issue, we will focus on defining the syntax for operators in bytescript, our script language for our compiler. Operators are special symbols that represent specific operations to be performed on data. They are essential for our script language because they provide a way to perform basic arithmetic, logical, and comparison operations on data, which are fundamental building blocks of any program.

This task involves:

- Researching common operators used in similar script languages
- Consulting with the development team to determine which operators should be included
- Identifying any additional operators specific to our script language

We will also need to define the syntax and usage for each operator, write a description of each operator, provide examples of how each operator can be used, specify the precedence and associativity of each operator, and ensure that the syntax is consistent and clear for all operators.

## Task List

- [x] Research common operators used in similar script languages.
	- [x] Consult with the development team to determine which common operators should be included in this script language.
	- [x] Identify any additional operators specific to this script language.
	- [x] Compare the operators used in this script language with those used in similar script languages.
	- [x] Evaluate the benefits and drawbacks of including or excluding certain operators.
- [x] Define the syntax and usage for each operator in the script language.
	- [x] Write a description of each operator, including its syntax and usage.
	- [x] Provide examples of how each operator can be used in the script language.
	- [ ] Test each operator to ensure that it works correctly and consistently.
		- [x] Create skeleton CLI project which can be compiled with `CMake`
		- [x] Create build and clean scripts for compiling bsc (ByteScript Compiler)
		- [ ] Add a test directory to create a place to put some of the input bytescript source files.
		- [ ] Test compiled bsc with outputting simple tokens as text output to the console.
		- [ ] Create additional tests unit for each of the operators which just looks for the operator in the input
	- [ ] Document any known issues or limitations with each operator.
- [ ] Specify the precedence and associativity of each operator in the script language.
	- [ ] Determine the order in which operators should be evaluated when multiple operators are used in an expression.
	- [ ] Specify whether each operator is left-associative or right-associative.
	- [ ] Test different combinations of operators to ensure that they are evaluated correctly according to their precedence and associativity.
	- [ ] Document any known issues or limitations with the precedence and associativity of operators.

## Documentation

As part of this task, we will also document the syntax and semantics of the operators in the script language for our compiler. This documentation will include the definitions, categories, and rules of the operators, as well as the examples and explanations of how they are used and evaluated in the source code. This documentation will help us, and other developers understand the logic and functionality of each operator in the script language.

To keep our documentation organized and accessible, we will create a new directory in our compiler to store our reference documentation for this task. The directory will be named `operators` and will be located under the `docs` directory. The directory will contain a text file named `operators.md` that will contain the syntax and semantics of the operators in the script language, along with their examples and explanations. The directory will also contain any other relevant files or resources that we use or create during our research, such as links, notes, or diagrams.

Here is an example file structure for our documentation:

```
bytescript/
├── docs/
│   ├── compiler/
│   │   ├── lexer/
│   │   │   ├── operators/
│   │   │   │   ├── operators.md
│   │   │   │   ├── operators.txt
│   │   │   │   └── ...
│   │   │   └── ...
│   │   └── ...
│   └── ...
└── ...
```

To create and update the documentation, we will use a text editor such as Visual Studio Code or Notepad++. We will follow a consistent format and style for writing the documentation, such as using headings, bullet points, indentation, and comments. We will also use proper grammar, spelling, and punctuation to ensure clarity and readability. We will review and revise the documentation as needed to ensure accuracy and completeness.

### Types of operators

The types of operators in the script language are:

- [**Arithmetic operators**](https://en.wikipedia.org/wiki/Arithmetic#Arithmetic_operations): These operators perform basic mathematical operations on numeric operands, such as addition, subtraction, multiplication, and division. Examples of arithmetic operators are `+`, `-`, `*`, and `/`. For example, `2 + 3` returns `5`, `4 - 2` returns `2`, `3 * 4` returns `12`, and `6 / 2` returns `3`.
- [**Relational operators**](https://en.wikipedia.org/wiki/Relational_operator): These operators compare two operands and return a Boolean value indicating their relationship, such as equal, not equal, greater than, or less than. Examples of relational operators are `==`, `!=`, `>`, and `<`. For example, `2 == 3` returns `false`, `4 != 2` returns `true`, `3 > 4` returns `false`, and `6 < 2` returns `false`.
- [**Logical operators**](https://en.wikipedia.org/wiki/Logical_connective): These operators perform logical operations on Boolean operands, such as conjunction, disjunction, or negation. Examples of logical operators are `&&`, `||`, and `!`. For example, `(2 == 3) && (4 != 2)` returns `false`, `(3 > 4) || (6 < 2)` returns `false`, and `!(6 < 2)` returns `true`.
- [**Assignment operators**](https://en.wikipedia.org/wiki/Assignment_(computer_science)): These operators assign a value to a variable or modify the value of a variable by performing an operation on it. Examples of assignment operators are `=`, `+=`, `-=`, `*=`, and `/=`. For example, if we have a variable `x = 2`, then after executing the statement `x += 3`, the value of x will be `5`.

By understanding the different types of operators and how they can be used in our script language, we can write clear and correct expressions that perform the desired operations on data.

### Rules for using operators

The rules for using operators in expressions are:

- Operators can only be applied to operands of compatible types. For example, arithmetic operators can only be applied to numeric operands, and logical operators can only be applied to Boolean operands.
- Operators have different levels of precedence, which determine the order in which they are evaluated when multiple operators are used in an expression. For example, `*` has higher precedence than `+`, so `2 + 3 * 4` is evaluated as `2 + (3 * 4)`, not `(2 + 3) * 4`.
- Operators have associativity, which determines how they are grouped when multiple operators of the same precedence are used in an expression. For example, `-` has left associativity, so `5 - 3 - 2` is evaluated as `(5 - 3) - 2`, not `5 - (3 - 2)`.

### Precedence and Associativity of Operators

The precedence and associativity of operators determine the order in which they are evaluated when multiple operators are used in an expression.

#### Precedence

The precedence of operators determines the order in which they are evaluated when multiple operators are used in an expression. Operators with higher precedence are evaluated before operators with lower precedence.

The precedence of operators in our script language follows the standard mathematical conventions. For example, multiplication and division have higher precedence than addition and subtraction, so `2 + 3 * 4` is evaluated as `2 + (3 * 4)`, not `(2 + 3) * 4`.

#### Associativity

The associativity of operators determines how they are grouped when multiple operators of the same precedence are used in an expression. Operators can be either left-associative or right-associative.

Left-associative operators are grouped from left to right. For example, the subtraction operator `(-)` is left-associative, so `5 - 3 - 2` is evaluated as `(5 - 3) - 2`, not as `5 - (3 - 2)`.

Right-associative operators are grouped from right to left. For example, the assignment operator `(=)` is right-associative, so `x = y = z` is evaluated as `x = (y = z)`, not as `(x = y) = z`.

#### Precedence and Associativity Table

The table below shows the precedence and associativity of operators in our script language. Operators with higher precedence are evaluated before operators with lower precedence. Operators with the same precedence are grouped according to their associativity.

| Operator | Description | Precedence | Associativity |
|----------|-------------|------------|---------------|
| !        | Logical NOT | Highest    | Right         |
| * / %    | Multiplication, division, and remainder | High   | Left          |
| + -      | Addition and subtraction    | Medium | Left          |
| < > <= >= | Relational comparison       | Low    | Left          |
| == != === !==  | Equality and inequality     | Lower  | Left          |
| & \| ^ ~ << >> >>>  | Bitwise operations         | Lower  | Left          |
| &&       | Logical AND                 | Lowest | Left          |
| \|\|     | Logical OR                  | Lowest | Left          |
| ??       | Nullish coalescing          | Lowest | Right         |
| ? :      | Ternary conditional         | Lowest | Right         |
| = += -= *= /= %=  | Assignment and compound assignment | Lowest | Right |

To change the order of evaluation or grouping of operators, we can use parentheses to override the precedence or associativity. For example, `(2 + 3) * 4` is evaluated as `20`, not as `14`, and `5 - (3 - 2)` is evaluated as `4`, not as `0`.

By understanding the precedence and associativity of operators, we can write clear and correct expressions in our script language.

**Comment by ZoeDreams** [comment]
- [ ] Research common operators in similar script languages. Add to `operators.md`.
- [ ] Consult with the development team to determine which common operators to include. Document in `operators.md`.
- [ ] Identify any additional operators specific to this script language. Add to `operators.md`.
- [ ] Compare operators with those in similar script languages. Evaluate benefits and drawbacks. Document in `operators.md`.
- [ ] Define syntax and usage for each operator. Document in `operators.md`.
- [ ] Write a description of each operator, including syntax, usage, and examples. Add to `operators.md`.
- [ ] Test each operator with different operands and values. Document test cases and results in `operators.md`.
- [ ] Document any known issues or limitations with each operator. Add to `operators.md`.
- [ ] Specify precedence and associativity of each operator. Document in `operators.md`.
- [ ] Determine order of evaluation when multiple operators are used. Add rules to `operators.md`.
- [ ] Test different combinations of operators for correct evaluation. Add test cases and results to `operators.md`.
- [ ] Document any known issues or limitations with precedence and associativity. Add to `operators.md`.
- [ ] Create reference documentation for syntax and semantics of operators. Save in `operators.md`.
- [ ] Review and revise documentation for accuracy and completeness.
- [ ] Update issue status and notify development team when task is completed.
